from com.android.monkeyrunner import MonkeyRunner, MonkeyDevice
device = MonkeyRunner.waitForConnection(5,'24DBAC03668A')
device.wake()
device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
device.press('KEYCODE_BACK',MonkeyDevice.DOWN_AND_UP)
result = device.takeSnapshot()
result.writeToFile('C:/T-Mobile/Development/Gibbon/GibbonGUI/Report/6-6-24DBAC03668A/ScreenShots/currentScreen-2012-06-06_01-35-54-PM.png' ,'png')
myfile = open('C:/T-Mobile/Development/Gibbon/GibbonGUI/py/EndFlag.txt','w')
myfile.write('1')
myfile.flush()
myfile.close()
